### ISSUE TITLE
Support .inc file

### ISSUE THREAD

**Issue by victoreduardobarreto** [gerardroche/sublime-php-grammar#102]
Hello,

Your plugin would can support .inc file.
In old php projects has inc files and the sublimetext don't understand this extension.

Thanks.

**Comment by gerardroche** [comment]
The `inc` filetype was supported in an earlier version, but it was removed because it conflicts with some other languages. 

Ref: https://github.com/gerardroche/sublime-php-grammar/commit/851c23746d329101b126a0c510267ba8b2fb6437

You can custom set a syntax to use with any filetype. It's a one-time configuration:

* open the file with the file type you want to use custom syntax for e.g. a `.inc` file
* select the syntax menu in the bottom right on the status bar
* select the syntax you want to use for the filetype e.g. PHP
