### ISSUE TITLE
No HTML syntax highlighting

### ISSUE THREAD

**Issue by svivian** [gerardroche/sublime-php-grammar#39]
Any HTML that is outside PHP tags is not getting highlighted. Tags, attributes etc just come up black. The default PHP syntax highlighting has this (plus CSS/JS where appropriate).

Using ST build 3083 (latest stable). Using the "Lazy" colour scheme but changing it doesn't make a difference - the HTML is all one colour.

**Comment by gerardroche** [comment]
This is fixed in the latest build, 3095. Use the HTML syntax for versions < 3084/3095. 

Build 3084 introduced a new syntax definition file format and between 3084 and 3095 many syntaxes were refactored and improved. 

Prior to build 3084 the HTML syntax, which included the PHP syntax, loads .php files. In the latest build, 3095, it's done properly, the PHP syntax, which includes the HTML syntax, loads .php files.
